2022-10-14 13:57:10,035 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters']
2022-10-14 13:57:10,037 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters', 'get_credentials']
2022-10-14 13:57:10,068 DEBUG    root            Running [gcloud.container.clusters.get-credentials] with arguments: [NAME: "acc-cluster"]
2022-10-14 13:57:10,073 DEBUG    root            (gcloud.container.clusters.get-credentials) One of [--zone, --region] must be supplied: Please specify location.
Traceback (most recent call last):
  File "/Users/ledemn/Desktop/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/ledemn/Desktop/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/Users/ledemn/Desktop/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 113, in Run
    cluster, cluster_ref = _BaseRun(args, self.context)
  File "/Users/ledemn/Desktop/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 37, in _BaseRun
    location = location_get(args)
  File "/Users/ledemn/Desktop/google-cloud-sdk/lib/googlecloudsdk/command_lib/container/container_command_util.py", line 243, in GetZoneOrRegion
    ['--zone', '--region'], 'Please specify location')
googlecloudsdk.calliope.exceptions.MinimumArgumentException: One of [--zone, --region] must be supplied: Please specify location.
2022-10-14 13:57:10,074 ERROR    root            (gcloud.container.clusters.get-credentials) One of [--zone, --region] must be supplied: Please specify location.
